# Site settings
title: Personal Webpage 
subtitle: of Dwaipayan Dasgupta
email: youremailaddress@gmail.com
description: A FREE AND FULLY RESPONSIVE SITE TEMPLATE
baseurl: "" #"/editorial-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://dwaipayandasgupta.github.io" # the base hostname & protocol for your site
author:
street_address: 339 Zeanah Engineering Complex\ 863 Neyland Drive
city: Knoxville
state: TN
zip_code: 37996
country: #United States of America
phone: (865) 974-7568

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
